# Build and test project using Android 13 (API 33)
name: Android CI (API 33 only)

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_HOME: /usr/local/lib/android/sdk
      GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2g -Dorg.gradle.daemon=false -Dfile.encoding=UTF-8"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Install Android SDK (API 33 only)
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true
          cmdline-tools-version: 12266719
          packages: |
            platform-tools
            platforms;android-33
            build-tools;33.0.2

      - name: Write local.properties
        run: bash .github/scripts/write-local-properties.sh

      - name: Gradle help (sanity)
        run: ./gradlew -q help

      - name: Assemble :app
        run: ./gradlew :app:assembleDebug --stacktrace --no-daemon --console=plain

      - name: Unit tests
        run: ./gradlew :app:testDebugUnitTest --stacktrace --no-daemon --console=plain

      - name: Paparazzi (if available)
        run: |
          if ./gradlew :app:tasks --all | grep -q "recordPaparazziDebug"; then
            ./gradlew :app:recordPaparazziDebug --stacktrace --no-daemon --console=plain
          else
            echo "No Paparazzi task found – skipping."
          fi

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: |
            **/build/test-results/**/*
            **/build/reports/tests/**/*
          if-no-files-found: warn

      - name: Upload Paparazzi snapshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: paparazzi-snapshots
          path: |
            **/build/paparazzi/**/*
          if-no-files-found: warn
