# CI pipeline ensuring reliable Android SDK setup and tests
name: Android CI

on:
  push: { branches: ["**"] }
  pull_request: { branches: ["**"] }

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_HOME: /usr/local/lib/android/sdk
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: gradle/actions/setup-gradle@v3

      - name: Install Android cmdline-tools
        run: |
          sudo mkdir -p $ANDROID_SDK_ROOT
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-12266719_latest.zip -O /tmp/clt.zip
          sudo unzip -o -q /tmp/clt.zip -d /usr/local/lib/android/
          sudo mkdir -p ${ANDROID_SDK_ROOT}/cmdline-tools
          sudo rm -rf ${ANDROID_SDK_ROOT}/cmdline-tools/16.0 || true
          sudo mv /usr/local/lib/android/cmdline-tools ${ANDROID_SDK_ROOT}/cmdline-tools/16.0
          sudo ln -sf ${ANDROID_SDK_ROOT}/cmdline-tools/16.0 ${ANDROID_SDK_ROOT}/cmdline-tools/latest
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install SDK packages
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          ${ANDROID_SDK_ROOT}/platform-tools/adb --version

      - name: Write local.properties
        run: |
          echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties
          cat local.properties

      - name: Grant Gradle wrapper
        run: chmod +x ./gradlew

      - name: Assemble
        run: ./gradlew :app:assembleDebug --stacktrace --no-daemon --console=plain

      - name: Unit tests
        run: ./gradlew testDebug --stacktrace --no-daemon --console=plain

      - name: Paparazzi record
        run: ./gradlew recordPaparazziDebug --stacktrace --no-daemon --console=plain

      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: |
            **/build/reports/tests/testDebugUnitTest/**
            **/build/test-results/testDebugUnitTest/**

      - name: Upload Paparazzi screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-screenshots-paparazzi
          path: app/out/paparazzi/**
