# CI pipeline building and testing the app with reliable Android SDK setup
name: Android CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_HOME: /usr/local/lib/android/sdk
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      # Install commandline tools and ensure sdkmanager works
      - name: Install Android CMDline tools & accept licenses
        run: |
          sudo mkdir -p $ANDROID_SDK_ROOT
          yes | sudo ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses || true || :
          # Some runners have an older "latest" alias; install a known good revision and re-run licenses.
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-12266719_latest.zip -O /tmp/clt.zip
          sudo unzip -o -q /tmp/clt.zip -d /usr/local/lib/android/
          sudo rm -rf ${ANDROID_SDK_ROOT}/cmdline-tools/16.0 || true
          sudo mkdir -p ${ANDROID_SDK_ROOT}/cmdline-tools
          sudo mv /usr/local/lib/android/cmdline-tools ${ANDROID_SDK_ROOT}/cmdline-tools/16.0 || true
          sudo ln -sf ${ANDROID_SDK_ROOT}/cmdline-tools/16.0 ${ANDROID_SDK_ROOT}/cmdline-tools/latest
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --licenses

      # INSTALL PACKAGES AS SEPARATE ARGS (prevents the "combined string" bug)
      - name: Install Android SDK packages
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"
          ${ANDROID_SDK_ROOT}/platform-tools/adb --version

      - name: Write local.properties with SDK path
        run: .github/scripts/write-local-properties.sh

      - name: Grant Gradle wrapper execute permission
        run: chmod +x ./gradlew

      - name: Build (assemble)
        run: ./gradlew :app:assembleDebug --stacktrace --no-daemon

      - name: Unit tests
        run: ./gradlew testDebug --stacktrace --no-daemon

      - name: Paparazzi record
        run: ./gradlew recordPaparazziDebug --stacktrace --no-daemon

      - name: Upload unit test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-reports
          path: |
            **/build/reports/tests/testDebugUnitTest/**
            **/build/test-results/testDebugUnitTest/**

      - name: Upload Paparazzi screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-screenshots-paparazzi
          path: app/out/paparazzi/**
