# CI pipeline building and testing the app with Paparazzi snapshots
name: Android CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Install Android SDK tools
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      - name: Accept SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Build (assemble)
        run: ./gradlew :app:assembleDebug --stacktrace # compile the app

      - name: Unit tests
        run: ./gradlew testDebug --stacktrace # execute unit tests

      - name: Paparazzi record
        run: ./gradlew recordPaparazziDebug --stacktrace # generate screenshots

      - name: Upload unit test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-reports
          path: |
            **/build/reports/tests/testDebugUnitTest/**
            **/build/test-results/testDebugUnitTest/**

      - name: Upload Paparazzi screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-screenshots-paparazzi
          path: app/out/paparazzi/**
